### ISSUE TITLE
Search for "München" didn't work but "Muenchen" does

### ISSUE THREAD

**Issue by navtsi** [jdaehne/GoogleStoreLocator#11]
If I'm searching for Cities with Umlauts the seach didn't find anything, but without it works.

BTW: Seaching for ZIP-Codes didn't work also. Changing line 211 in googlestorelocator didn't fix it for me.

**Comment by jdaehne** [comment]
@navtsi this is a Google-API-Bug. Searching for "München" will find no result if there is no Country input as well. You can fix this by setting the `&region=de` property. (Fixed that in 2.0.1).
With region set to `de` "München" will result in "Munich, Germany".

**Comment by navtsi** [comment]
I have region set to »de«. Here my call:
`[[!GoogleStoreLocator?
					&parents=`9`
					&tvNameZipcode=`expert_plz`
					&tvNameCity=`expert_ort`
					&tvNameStreet=`expert_strasse`
					&tvNameCountry=`expert_land`
					&zoom=`6`
					&latCenter=`51.289406`
					&lngCenter=`10.442076`
					&mapCSS=`height: 570px`
					&tplStore=`tpl_searchexpert_item`
					&tplForm=`tpl_searchexperts_form`
					&region=`de`
					&sortby=`longtitle`
					&includeTVs=`expert_anrede`
				]]`

**Comment by navtsi** [comment]
I have 2.0.0 installed. There can I download 2.0.1. There is no update message in MODx.

**Comment by navtsi** [comment]
After a little google research seams, there is noch valid solution for this. Some people says that they replace ü with ue before sending. Is it possible to integrate a javascript before sending? Sorry I'm not a developer.

**Comment by jdaehne** [comment]
Version 2.0.1 is now available in the package-manager...

**Comment by navtsi** [comment]
Now it works. Thanks a lot.
