### ISSUE TITLE
Sort by Distance

### ISSUE THREAD

**Issue by Quentin100** [jdaehne/GoogleStoreLocator#13]
Hi, 

I love and am equally frustrated by this Extra! I had it working in the 1.x version, but wanted to update the code so went for upgrade. All good, until I get the results and find it no longer sorts by distance from the searched location, it seems to default to menuindex and I can't get it to list the Stores by Distance from the searched location (which it was doing in version 1.x). 

I've updated to 2.0.1 and got it outputting on a test page no problems, and shows the correct distances from the search location. Is there something I am missing/doing wrong, or does version 2.x not support sorting by distance?

Thanks,

Quentin

![image](https://user-images.githubusercontent.com/22519836/47568563-5e132680-d929-11e8-8daf-1205047851f2.png)

**Comment by jdaehne** [comment]
@Quentin100 oh! Yes, this is a bug. Thanks for the report. I fixed it in Version [2.0.2](fa5e073c01fffff6ce2831b75cd2dd9ea25cfa31)
This Version is now available in the MODX  Package-Manager.

**Comment by Quentin100** [comment]
Works perfectly! Thanks for extra fast fix. Back in love with this Extra
