### ISSUE TITLE
getPage not working

### ISSUE THREAD

**Issue by kurokh** [jdaehne/GoogleStoreLocator#14]
Hi, great snippet, thanks for work, i'm trying make pagination, because i have more than 200 stores, but i haven't result, i trying like that
`[[!getPage?
    &element=GoogleStoreLocator
    &parents=5
    &debug=1
    &limit=2
    &totalVar=gsl.totalResult
]]
<div class="pageNav">[[!+page.nav]]</div>`

also like that 
`[[!getPage?
    &element=GoogleStoreLocator
    &parents=5
    &debug=1
    &limit=2
    &totalVar=gsl.totalResult
]]
[[!+gsl.stores]]
<div class="pageNav">[[!+page.nav]]</div>
`
but pagination placeholder is always empty http://joxi.ru/Q2KdOeFLWGMzAj maybe i forgot something?
http://pure.sb200y.tmweb.ru/test.html

**Comment by jdaehne** [comment]
I will try to look into it on friday.

**Comment by kurokh** [comment]
thanks. i'll be waiting

**Comment by jdaehne** [comment]
@ak215 This should be fixed with the new Version 2.0.3!
