### ISSUE TITLE
Installed but postcode not converting

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/GoogleStoreLocator#19]
I have installed this extra. Created the Google API and enabled the relevant services and created some stores, and a map is created but doesn't have the long and lat for any of the stores. 

I'm not sure what I am missing in setting this up but it doesn't appear to be working as expected.  This is my call.

`[[!GoogleStoreLocator? &parents=`[[*id]]` &latCenter=`51.5213992` &lngCenter=`-0.7123154` &zoom=`12` &unit=`M` ]]
[[!+gsl.form]]
[[!+gsl.map]]
[[!+gsl.message]]
[[!+gsl.stores]]`

Using version 2.0.3 of extra, on site with MODX 2.7.2 and PHP 7.2.

**Comment by crimsonpixel** [comment]
Get this error message in the logs

`[2020-07-20 16:11:15] (ERROR @ /home/domain/public_html/nodular/components/googlestorelocator/model/googlestorelocator/googlestorelocator.class.php : 195) [GoogleStoreLocator] Could not get Geo-Data of Address: XXXX  Errormessage: API keys with referer restrictions cannot be used with this API.`

This are no restrictions other than to the domain name.

**Comment by jdaehne** [comment]
@crimsonpixel try to remove all the restrictions. If it works then your restrictions are not correct. The error-message is from the Google-API telling, that you are not allowed to do this action: access denied.
So i would guess it is your restriction.

**Comment by crimsonpixel** [comment]
OK the restrictions have been lifted and now converts the postcode.  

Stores do now appear on map if zoomed out ;)

Thanks for feedback.
