### ISSUE TITLE
Search by ZipCode only does not return any results

### ISSUE THREAD

**Issue by chrissen-77** [jdaehne/GoogleStoreLocator#9]
Using the search with zipcode only does not return any results even though appropriate result sets do exist. Searching by city name or city and zipcode works just fine on the other hand. Bug occurs irrespective of result set size (one of my projects has 1500+ address sets, the other one only 60).

**Comment by chrissen-77** [comment]
Own feedback. I change the googlestorelocator.class.php for Location = DE. Now i got Results, similar like #8. Same Problems here with Ulm, shows diffrent place in USA. I think there is a location bug

**Comment by jdaehne** [comment]
Fixed by version 2.0.1
